version: '3.7'
services:
  rt:
    container_name: proxy    
    build: .
    image: $REG/rt/$SRV:$RT
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 81:8080/tcp
      # - 8080:80/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/conf:rw
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test4.rule=Host(`traefik.ixomaxip.keenetic.pro`)"
      - "traefik.http.routers.test4.service=api@internal"
      - "traefik.http.routers.test4.middlewares=admin"
      - "traefik.http.routers.test4.tls.certresolver=le"
      - "traefik.http.routers.test4.entrypoints=https"
      - "traefik.http.middlewares.admin.basicauth.users=admin:$$apr1$$UcOFJ2TN$$.0eVxYT0hNb7lSj7owwXV0"
      - "traefik.http.services.test4-test4.loadbalancer.server.port=65535"
      # - "traefik.http.routers.test3.rule=Host(`home.ixomaxip.com`) && (PathPrefix(`/traefik`) || PathPrefix(`/api`))"
      # # - "traefik.http.routers.test3.rule=PathPrefix(`/traefik`) || PathPrefix(`/api`)"
      # # - "traefik.http.routers.test3-http.rule=PathPrefix(`/dev/traefik`) || HeadersRegexp(`Referer`, `.*\/dev\/traefik\/.*`)"
      # - "traefik.http.routers.test3.service=api@internal"
      # - "traefik.http.routers.test3.entrypoints=https"
      # - "traefik.http.routers.test3.tls=true"
      # - "traefik.http.routers.test3.middlewares=test3-strip"
      # - "traefik.http.middlewares.test3-strip.stripprefix.prefixes=/traefik"
      # - "traefik.http.services.test3-traefik.loadbalancer.server.port=65535"
      # - "traefik.http.routers.test2.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      # - "treafik.http.routers.test2.service=api@internal"
      # - "traefik.http.routers.test2.middlewares=test2-auth"
      # - "traefik.http.middlewares.test2-auth.basicauth.users=admin:$$apr1$$UcOFJ2TN$$.0eVxYT0hNb7lSj7owwXV0"
      # - "traefik.http.routers.test1.entrypoints=https"     
      # - "traefik.http.routers.test1.rule=PathPrefix(`/traefik`)"
      # - "traefik.http.routers.test1.middlewares=test1-stripprefix"
      # - "traefik.http.middlewares.test1-stripprefix.stripprefix.prefixes=/traefik"
      # - "traefik.http.routers.test1.tls=true"
      # - "traefik.http.routers.test1.service=api@internal"
      # - "traefik.http.services.test1-traefik.loadbalancer.server.port=888"
      # - "traefik.http.routers.test0.entrypoints=https"
      # - "traefik.http.routers.test0.rule=Host(`traefik.local`)"
      # - "traefik.http.routers.test0.tls=true"
      # - "traefik.http.routers.test0.tls.certresolver=letsEncrypt"
      # - "traefik.http.routers.test0.service=api@internal"
      # - "traefik.http.services.test0-traefik.loadbalancer.server.port=8080"
    restart: always

networks:
  default:
    external:
      name: rt_default