version: '3.7'
services:
  rt:
    container_name: proxy    
    build: .
    image: $REG/rt/$SRV:$RT
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 81:8080/tcp
      # - 8080:80/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/conf:rw
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.test2.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      # - "treafik.http.routers.test2.service=api@internal"
      # - "traefik.http.routers.test2.middlewares=test2-auth"
      # - "traefik.http.middlewares.test2-auth.basicauth.users=admin:$$apr1$$UcOFJ2TN$$.0eVxYT0hNb7lSj7owwXV0"
      # - "traefik.http.routers.test1.entrypoints=https"     
      - "traefik.http.routers.test1.rule=PathPrefix(`/traefik`)"
      - "traefik.http.routers.test1.middlewares=test1-stripprefix"
      - "traefik.http.middlewares.test1-stripprefix.stripprefix.prefixes=/traefik"
      # - "traefik.http.routers.test1.tls=true"
      - "traefik.http.routers.test1.service=api@internal"
      - "traefik.http.services.test1-traefik.loadbalancer.server.port=888"
      # - "traefik.http.routers.test0.entrypoints=https"
      # - "traefik.http.routers.test0.rule=Host(`traefik.local`)"
      # - "traefik.http.routers.test0.tls=true"
      # - "traefik.http.routers.test0.tls.certresolver=letsEncrypt"
      # - "traefik.http.routers.test0.service=api@internal"
      # - "traefik.http.services.test0-traefik.loadbalancer.server.port=8080"

    restart: always

networks:
  default:
    external:
      name: rt_default