version: '3.7'
services:
  rt:
    container_name: proxy    
    build: .
    image: $REG/rt/$SRV:$RT
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 81:8080/tcp
      - 8080:80/tcp
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./conf:/conf:rw
      - ./conf/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./conf/acme.json:/acme.json
    restart: always

networks:
  default:
    external:
      name: rt_default