
log:
  level: DEBUG

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  http:
    address: :80
  https:
    address: :443

providers:
  # file:
  #   watch: true
  #   filename: /conf/dynamic_conf.yml
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

http:
  routers:
    http-catchall:
      rule: hostregexp(`{host:.+}`)
      entrypoints:
      - http
      middlewares:
      - redirect-to-https
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false


certificatesResolvers:
  le:
    acme:
      email: ixomaxip@gmail.com
      storage: acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http